# This is a generated file. Not intended for manual editing.
services:
  wisave-portal:
    build:
      context: "/Users/jakubchwastek/Desktop/Projects/WiSave.Portal"
      dockerfile: "WiSave.Portal.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/WiSave.Portal.WebApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "wisave.portal:dev"
    ports: []
    volumes:
    - "/Users/jakubchwastek/Desktop/Projects/WiSave.Portal/WiSave.Portal.WebApi:/app:rw"
    - "/Users/jakubchwastek/Desktop/Projects/WiSave.Portal:/src:rw"
    - "/Users/jakubchwastek/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
