# This is a generated file. Not intended for manual editing.
services:
  wisave-portal:
    build:
      context: "/Users/jakubchwastek/Desktop/Projects/WiSave.Portal"
      dockerfile: "WiSave.Portal.WebApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "wisave.portal:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "/Users/jakubchwastek/Desktop/Projects/WiSave.Portal/WiSave.Portal.WebApi:/app:rw"
    - "/Users/jakubchwastek/Desktop/Projects/WiSave.Portal:/src:rw"
    - "/Users/jakubchwastek/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/jakubchwastek/.local/share/JetBrains/RiderRemoteDebugger/2025.1.2/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/jakubchwastek/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/jakubchwastek/Library/Logs/JetBrains/Rider2025.1/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_15_15_40_42:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
